language: java
jdk: openjdk8
after_success:
- "./gradlew uploadArchives"
- curl -u $JENKINS_USER:$JENKINS_PASS -X POST https://jenkins.nulab.co.jp/job/BLG-backlog-api-v2-test/build
notifications:
  webhooks:
    urls:
    - https://nulab-inc.com/hubot/travis?room=44
    on_success: change
