name: Build and Release

on:
  push:
    branches: [ use-jreleaser ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew build test

      - name: Import GPG secret key
        env:
          GPG_TTY: /dev/tty
        run: |
          echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" | base64 --decode | gpg --batch --import

      - name: Run JReleaser
        run: ./gradlew jreleaserFullRelease -Djreleaser.signing.mode=COMMAND
        env:
          JRELEASER_SIGNING_MODE: COMMAND
          JRELEASER_GPG_KEYNAME: ${{ secrets.SIGNING_KEY_ID }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.OSSRH_USER_NAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}
